apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  labels:
    app: bot-qdrant
    component: storage
spec:
  selector:
    app: bot-qdrant
    component: storage
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
  type: ClusterIP